# -*- coding: utf-8 -*-
"""Аналитика РусЭкспресс, v. 5.0

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wHECx9Qpo4Je9wALqQX6Y0lvjOCNrfBx

# GIT
"""

"""# Контейнер свойств"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile properties.py
# class Baseproperties:
#   directories # справочники, словарь
#   version
#   approvedStatuses
#   profitStatuses
#   debitStatuses
# 
# 
# class Tempproperties:
#   pass
# 
#

"""# Подключения, открытия файлов"""

class ConnectAPI:
  def openAPI():

class ConnectDB:
  def openDB(self):

  def closeDB(self):

class Openfiles:
  def openFile(self):
    if csv:

    elif xml:

class Connections:
  openAPI....

"""# Работа с базой данных"""

class Database:
  def createDB

  def createTables

  def createColumns

class ReportDBSender: # отправка финального запроса в базу
  def sendReportQuery(self):

class Directories:
  def updateDirectory:

"""# Сбор данных"""

class OrdersData:
  def getDataFromOrders



class ChannelsData:
  def isReportUpdate():

  def getDataFromChannel(self):

"""# Обработка данных"""

class ReportDataChangerFunc:

  def changeCats

  def changePriceSegments

  def changeSalePrice

  def namesTo01

class ReportDataChanger(ReportDataChangerFunc):
  for ...

"""# Расчеты в итоговую таблицу"""

class Calculates:
  def calcApprovedOrdersSum()

  def calcPaidProductsIncome()

  def calcPaidDeliveryIncome()

  def calcApprovedProductsExpense()

  def calcApprovedDeliveryExpense()

  def calcApprovedOperationsExpense()

  def calcDebit():
  
  def calcProfit():

  def calcFutureProfit():
  
  def calcReportData():
    calcApprovedOrdersSum
    .....

"""# Builder"""

class Reportdates:
  def calcCurDate:

class Report:
  def updateReport:

"""# Запуск"""

if __name__ == '__main__':
  
  dates = ReportDates()
  connect = Connections()
  bd = Database(connect)
  report = Report(dates, connect)
  connect = Connections(connect)